#!/usr/bin/env bash
# Write games/<game>/build_config.cfg — the settings that travel INSIDE an
# export, so a shipped game needs no environment set up on the target machine.
#
# WHY THIS EXISTS
#   A .desktop launcher does not inherit your shell environment, and Android has
#   no shell to export a variable from at all. Without this, a game installed
#   from a menu icon reaches no broker and silently publishes nothing — which
#   looks exactly like everything working. Baking the settings into the .pck is
#   the only mechanism that behaves identically on a desktop launcher, a Pi
#   autostart, and an Android APK.
#
#   QConfig layers it as:
#     defaults < res://build_config.cfg < user://config.cfg < environment
#   so a specific device can still override a baked value, and a dev shell
#   still wins over both.
#
# ⚠  A BAKED BUILD CONTAINS YOUR BROKER PASSWORD IN PLAIN TEXT.
#   Anyone holding the binary can read it with `strings`. That is the trade for
#   zero-setup installs on a private LAN. Do not publish a baked artifact.
#   Use --no-secrets for anything that leaves the house; dist/ is gitignored and
#   build_config.cfg is gitignored, so neither reaches the repository.
#
# Sources, in order of increasing precedence:
#   ~/.config/qgames/mqtt.env      (the file gen1 already uses)
#   MQTT_* / QGAMES_MQTT_* in the current environment
#
# Usage:
#   tools/bake_config.sh <game>|--all [--no-secrets]
#   tools/bake_config.sh --clean            remove every generated file
set -euo pipefail
cd "$(dirname "$0")/.."

ENV_FILE="${QGAMES_ENV_FILE:-$HOME/.config/qgames/mqtt.env}"
games() { for d in games/*/project.godot; do basename "$(dirname "$d")"; done; }

if [[ "${1:-}" == "--clean" ]]; then
    for g in $(games); do rm -f "games/$g/build_config.cfg"; done
    echo "removed every games/*/build_config.cfg"
    exit 0
fi

target="${1:-}"
no_secrets=0
[[ "${2:-}" == "--no-secrets" || "${1:-}" == "--no-secrets" ]] && no_secrets=1
[[ "$target" == "--no-secrets" ]] && target="--all"

if [[ -z "$target" ]]; then
    echo "usage: $(basename "$0") <game>|--all [--no-secrets]" >&2
    echo "       $(basename "$0") --clean" >&2
    exit 1
fi

# ── gather settings ─────────────────────────────────────────────────────────
# Read the env file WITHOUT exporting it into this shell, so a stray line in
# that file cannot clobber something here.
val() {
    local key="$1" out=""
    if [[ -f "$ENV_FILE" ]]; then
        out="$(sed -n "s/^[[:space:]]*${key}=//p" "$ENV_FILE" | tail -1)"
        out="${out%\"}"; out="${out#\"}"
    fi
    # environment wins over the file; QGAMES_-prefixed wins over bare
    [[ -n "${!key:-}" ]] && out="${!key}"
    local prefixed="QGAMES_${key}"
    [[ -n "${!prefixed:-}" ]] && out="${!prefixed}"
    printf '%s' "$out"
}

# Escape for a Godot ConfigFile string literal.
esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

VERSION="$(tools/version.sh)"
COMMIT="$(git rev-parse --short=7 HEAD 2>/dev/null || echo unknown)"
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

BROKER="$(val MQTT_BROKER)"
PORT="$(val MQTT_PORT)"; PORT="${PORT:-1883}"
USERNAME="$(val MQTT_USERNAME)"
PASSWORD="$(val MQTT_PASSWORD)"
PREFIX="$(val MQTT_TOPIC_PREFIX)"; PREFIX="${PREFIX:-qGames}"

write_one() {
    local g="$1" out="games/$1/build_config.cfg"
    {
        echo "; GENERATED by tools/bake_config.sh — do not edit, do not commit."
        echo "; Travels inside the export so the game needs no environment set up."
        echo ""
        echo "[build]"
        echo "version=\"$(esc "$VERSION")\""
        echo "commit=\"$(esc "$COMMIT")\""
        echo "built_at=\"$(esc "$BUILT_AT")\""
        if [[ $no_secrets -eq 0 && -n "$BROKER" ]]; then
            echo ""
            echo "[mqtt]"
            echo "broker=\"$(esc "$BROKER")\""
            echo "port=${PORT}"
            echo "username=\"$(esc "$USERNAME")\""
            echo "password=\"$(esc "$PASSWORD")\""
            echo "topic_prefix=\"$(esc "$PREFIX")\""
        fi
    } > "$out"
    chmod 600 "$out"
}

selected=()
if [[ "$target" == "--all" ]]; then
    mapfile -t selected < <(games)
else
    [[ -f "games/$target/project.godot" ]] || { echo "error: no such game 'games/$target'" >&2; exit 1; }
    selected=("$target")
fi

for g in "${selected[@]}"; do write_one "$g"; done

echo "baked version $VERSION into: ${selected[*]}"
if [[ $no_secrets -eq 1 ]]; then
    echo "  mqtt: omitted (--no-secrets)"
elif [[ -z "$BROKER" ]]; then
    echo "  mqtt: no broker found in $ENV_FILE or the environment — telemetry will publish nowhere"
else
    echo "  mqtt: $BROKER:$PORT as '${USERNAME:-<anonymous>}'  ⚠ credentials are IN the artifact"
fi
